const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={angle:0,beta:0,gamma:0,zero:0,held:false,image:null,points:[],referencePixels:0,result:null};
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));history.replaceState(null,'',`#${id}`);if(id==='history')renderHistory();scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));let toastTimer;function toast(m){let e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function incline(beta,gamma){let x=Math.abs(gamma)<45?Math.abs(beta):Math.abs(gamma);if(x>90)x=180-x;return Math.max(0,Math.min(90,x))}
function orientation(e){if(state.held||e.beta==null)return;state.beta=e.beta;state.gamma=e.gamma;let next=Math.max(0,incline(e.beta,e.gamma)-state.zero);state.angle=state.angle*.78+next*.22;updateAngle()}
function updateAngle(){let a=state.angle;$('#angleValue').textContent=`${a.toFixed(1)}°`;$('#needle').style.transform=`rotate(${-a}deg)`;let z=a<10?['FLAT','Flat press','Raise the bench for upper chest.']:a<20?['LOW INCLINE','Chest dominant','A subtle upper-chest emphasis.']:a<=30?['SWEET SPOT','Upper chest','Excellent range for incline chest press.']:a<=45?['HIGH INCLINE','Chest + shoulders','More front-deltoid involvement.']:['SHOULDER','Shoulder dominant','This is closer to a shoulder press.'];$('#zoneBadge').textContent=z[0];$('#zoneTitle').textContent=z[1];$('#zoneHint').textContent=z[2];$('#lrValue').textContent=`${state.gamma.toFixed(1)}°`;$('#fbValue').textContent=`${state.beta.toFixed(1)}°`;$('#bubble').style.transform=`translate(${Math.max(-115,Math.min(115,state.gamma*4))}px,${Math.max(-115,Math.min(115,state.beta*4))}px)`}
$('#sensorBtn').onclick=async()=>{try{if(typeof DeviceOrientationEvent==='undefined')throw Error('No orientation sensor detected');if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('Sensor permission was not granted');addEventListener('deviceorientation',orientation,true);$('#sensorPrompt').hidden=true;toast('Sensor active')}catch(e){toast(e.message)}};
$('#calibrateBtn').onclick=()=>{state.zero+=state.angle;state.angle=0;updateAngle();toast('Zero point calibrated')};$('#holdBtn').onclick=e=>{state.held=!state.held;e.currentTarget.textContent=state.held?'Resume':'Hold';toast(state.held?'Reading held':'Reading resumed')};$$('[data-angle-mode]').forEach(b=>b.onclick=()=>{$$('[data-angle-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#inclinePanel').hidden=b.dataset.angleMode!=='incline';$('#levelPanel').hidden=b.dataset.angleMode!=='level'});
function saved(){try{return JSON.parse(localStorage.getItem('measurapp-history')||'[]')}catch{return[]}}function saveMeasurement(x){let l=saved();l.unshift({...x,id:Date.now(),date:new Date().toISOString()});localStorage.setItem('measurapp-history',JSON.stringify(l.slice(0,100)));toast('Measurement saved')}$('#saveAngleBtn').onclick=()=>saveMeasurement({type:'Angle',value:`${state.angle.toFixed(1)}°`,icon:'∠'});
function renderHistory(){let l=saved(),r=$('#historyList');$('#clearHistory').hidden=!l.length;r.innerHTML=l.length?l.map(x=>`<article class="history-item"><span class="history-icon">${x.icon}</span><div><b>${x.type}</b><small>${new Date(x.date).toLocaleString()}</small></div><output>${x.value}</output></article>`).join(''):'<div class="empty">No saved measurements yet.<br>Your results will appear here.</div>'}$('#clearHistory').onclick=()=>{if(confirm('Delete all saved measurements?')){localStorage.removeItem('measurapp-history');renderHistory();toast('History cleared')}};

const canvas=$('#photoCanvas'),ctx=canvas.getContext('2d');function resetPhoto(){state.points=[];state.referencePixels=0;state.result=null;$('#referenceForm').hidden=false;$('#resultCard').hidden=true;setStep(1);drawPhoto();$('#tapHint').textContent='Tap two ends of the reference'}
$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let img=new Image();img.onload=()=>{state.image=img;let s=Math.min(1,1400/img.width);canvas.width=img.width*s;canvas.height=img.height*s;$('#cameraStart').hidden=true;$('#photoWorkspace').hidden=false;resetPhoto()};img.src=URL.createObjectURL(f)};
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}function distance(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}canvas.onpointerdown=e=>{if(!state.image||state.points.length>=4)return;state.points.push(point(e));drawPhoto();if(state.points.length===2)$('#tapHint').textContent='Enter the known length below';if(state.points.length===4)calculateCamera()};
function line(a,b,color,label){ctx.strokeStyle=color;ctx.lineWidth=Math.max(4,canvas.width/250);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();[a,b].forEach(p=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(7,canvas.width/170),0,7);ctx.fill()});ctx.font=`700 ${Math.max(18,canvas.width/45)}px system-ui`;ctx.fillStyle=color;ctx.fillText(label,(a.x+b.x)/2+10,(a.y+b.y)/2-10)}function drawPhoto(){if(!state.image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.image,0,0,canvas.width,canvas.height);if(state.points.length>=2)line(state.points[0],state.points[1],'#bafc45','REFERENCE');if(state.points.length>=4)line(state.points[2],state.points[3],'#43d8f7','MEASURED');else state.points.forEach((p,i)=>{if(i%2===0){ctx.fillStyle=i<2?'#bafc45':'#43d8f7';ctx.beginPath();ctx.arc(p.x,p.y,9,0,7);ctx.fill()}})}function setStep(n){$$('.stepper span').forEach((s,i)=>s.classList.toggle('on',i<n))}
$('#confirmReference').onclick=()=>{if(state.points.length<2)return toast('Mark both ends of the reference');let v=parseFloat($('#referenceValue').value);if(!(v>0))return toast('Enter a valid reference length');state.referencePixels=distance(state.points[0],state.points[1]);$('#referenceForm').hidden=true;$('#tapHint').textContent='Now tap two ends of the object';setStep(2)};function calculateCamera(){if(!state.referencePixels)return;let value=parseFloat($('#referenceValue').value)*distance(state.points[2],state.points[3])/state.referencePixels,unit=$('#cameraUnit').value;state.result={value,unit};$('#cameraResult').textContent=`${fmt(value)} ${unit}`;$('#resultCard').hidden=false;$('#tapHint').textContent='Measurement complete';setStep(3)}
$('#undoPoint').onclick=()=>{if(!state.points.length)return;if(state.points.length<=2){state.points.pop();state.referencePixels=0;$('#referenceForm').hidden=false;setStep(1)}else{state.points.pop();$('#resultCard').hidden=true;state.result=null;setStep(2)}drawPhoto()};$('#newPhoto').onclick=()=>{state.image=null;state.points=[];$('#photoWorkspace').hidden=true;$('#cameraStart').hidden=false;$('#photoInput').value=''};$('#saveCameraBtn').onclick=()=>state.result&&saveMeasurement({type:'Photo length',value:`${fmt(state.result.value)} ${state.result.unit}`,icon:'⌗'});

const units={length:{label:'Length',items:{mm:['Millimeter',.001],cm:['Centimeter',.01],m:['Meter',1],km:['Kilometer',1000],in:['Inch',.0254],ft:['Foot',.3048],yd:['Yard',.9144],mi:['Mile',1609.344]}},area:{label:'Area',items:{'cm²':['Square centimeter',.0001],'m²':['Square meter',1],'km²':['Square kilometer',1e6],'in²':['Square inch',.00064516],'ft²':['Square foot',.09290304],acre:['Acre',4046.856]}},volume:{label:'Volume',items:{ml:['Milliliter',.001],l:['Liter',1],'m³':['Cubic meter',1000],cup:['US cup',.236588],gal:['US gallon',3.785412]}},mass:{label:'Mass',items:{mg:['Milligram',1e-6],g:['Gram',.001],kg:['Kilogram',1],oz:['Ounce',.0283495],lb:['Pound',.453592]}},angle:{label:'Angle / slope',items:{deg:['Degree',1],rad:['Radian',180/Math.PI],grad:['Gradian',.9],percent:['Grade percent',null]}},temperature:{label:'Temperature',items:{c:['Celsius',1],f:['Fahrenheit',1],k:['Kelvin',1]}}},category=$('#categorySelect'),fromUnit=$('#fromUnit'),toUnit=$('#toUnit');Object.entries(units).forEach(([k,v])=>category.add(new Option(v.label,k)));
function populate(){let u=units[category.value].items;fromUnit.innerHTML=toUnit.innerHTML='';Object.entries(u).forEach(([k,v])=>{fromUnit.add(new Option(`${v[0]} (${k})`,k));toUnit.add(new Option(`${v[0]} (${k})`,k))});toUnit.selectedIndex=1;convert()}function temp(v,a,b){let c=a==='c'?v:a==='f'?(v-32)*5/9:v-273.15;return b==='c'?c:b==='f'?c*9/5+32:c+273.15}function angle(v,a,b){let d=a==='percent'?Math.atan(v/100)*180/Math.PI:v*units.angle.items[a][1];return b==='percent'?Math.tan(d*Math.PI/180)*100:d/units.angle.items[b][1]}function fmt(v){if(!Number.isFinite(v))return'—';return Math.abs(v)>=1e6||Math.abs(v)<.0001&&v!==0?v.toExponential(4):new Intl.NumberFormat(undefined,{maximumFractionDigits:6}).format(v)}function calc(v,a,b){if(category.value==='temperature')return temp(v,a,b);if(category.value==='angle')return angle(v,a,b);let d=units[category.value].items;return v*d[a][1]/d[b][1]}
function convert(){let v=parseFloat($('#fromValue').value),out=calc(v,fromUnit.value,toUnit.value);$('#toValue').textContent=fmt(out);$('#formulaText').textContent=`1 ${fromUnit.value} = ${fmt(calc(1,fromUnit.value,toUnit.value))} ${toUnit.value}`;$('#quickValues').innerHTML=[...toUnit.options].filter(o=>o.value!==fromUnit.value).slice(0,4).map(o=>`<div><span>${o.value}</span><b>${fmt(calc(v,fromUnit.value,o.value))}</b></div>`).join('')}category.onchange=populate;[$('#fromValue'),fromUnit,toUnit].forEach(x=>x.oninput=convert);$('#swapUnits').onclick=()=>{let a=fromUnit.value;fromUnit.value=toUnit.value;toUnit.value=a;convert()};populate();
let installPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));let initial=location.hash.slice(1);if(['angle','camera','convert','history'].includes(initial))go(initial);
